### ISSUE TITLE
Node.js 개인과제 피드백 - 정영훈 튜터

### ISSUE THREAD

**Issue by jyh7a** [fierceCry/sprat-Node.js-introduction#1]
개인 과제 하느라고 수고 많으셨습니다. 
전체적으로 비동기 처리 및 에러 처리를 깔끔하게 잘 작성해주셨습니다. 
git commit message만 convention을 검색해서 규칙에 맞게 작성해주세요!

아래는 프로젝트에 대한 피드백입니다.

---

### 1. 개발 (준비): 프로젝트 기본 세팅
- [x] 1. `README.md` 파일을 생성하여 간략한 프로젝트의 설명 및 실행 방법을 작성합니다.
- [x] 2. `.env` 파일을 이용해서 민감한 정보(DB 계정 정보 등)를 관리합니다.
- [x] 3. `.gitignore` 파일을 생성하여 `.env` ,`node_modules` 등
불필요하거나 민감한 정보가 Github에 올라가지 않도록 설정합니다.
- [x] 4. `.prettierrc` 파일을 생성하여 일정한 코드 형태를 유지할 수 있도록 설정합니다.
- [ ] 5. `package.json` 파일의 `scripts` 항목에 `dev` 라는 이름을 추가하여 [nodemon](https://myung-ho.tistory.com/95)을 이용해서 서버를 실행할 수 있도록 합니다.

### 1. Feedback
5. scripts에 dev 항목을 추가해 줍시다.
  ```bash
  "scripts": {
      "start": "node app.js",
      "dev": "nodemon app.js"
    },
  ```

<br/>

---

<br/>

### 2. 개발 (준비): 프로젝트 기본 세팅
- [x] 1. 상품 생성 API
- [x] 2. 상품 목록 조회 API
- [x] 3. 상품 상세 조회 API
- [x] 4. 상품 수정 API
- [x] 5. 상품 삭제 API

### 2. Feedback
1. 상품 생성 라우터 잘 작성하였습니다.  아래 몇 가지만 수정해 줍시다.
https://github.com/fierceCry/sprat-Node.js-introduction/blob/4f3da924372c42bbbc54d70c4aeadf188e56babd/src/routers/products.router.js#L37
- req.body 에서 사용하지 않는 status 가져올 필요가 없습니다.
https://github.com/fierceCry/sprat-Node.js-introduction/blob/4f3da924372c42bbbc54d70c4aeadf188e56babd/src/routers/products.router.js#L43
- 이미 상품이 있다면 409 Conflict 를 상태로 주는것이 더 좋습니다. 
https://github.com/fierceCry/sprat-Node.js-introduction/blob/4f3da924372c42bbbc54d70c4aeadf188e56babd/src/routers/products.router.js#L45
- req.body를 그대로 넘기면 req.body에 불필요한 값들이 들어 올 수 있기때문에 필요한 값들만 뽑아서 사용 하는것이 좋습니다.

2. 상품 생성시 비밀번호 해싱 
https://github.com/fierceCry/sprat-Node.js-introduction/blob/4f3da924372c42bbbc54d70c4aeadf188e56babd/src/routers/products.router.js#L45
- 이 부분은 추가적인 구현 부분으로 bcrypt 등 해싱 모듈을 사용해서 상품 생성 전에 비밀번호를 해싱합시다.

4. 상품 수정시에도 req.body 값을 모두 주기 보다는 필요한 값들을 확인하고 업데이트 하는 로직으로 변경.
https://github.com/fierceCry/sprat-Node.js-introduction/blob/4f3da924372c42bbbc54d70c4aeadf188e56babd/src/routers/products.router.js#L111-L113
req.boyd에 사용자가 어떤 값을 넣어서 보냈는지 모르기 때문에 이 부분도 필요한 데이터만 추출해서 상품을 수정하는 코드로 변경해 주세요.

<br/>

---

<br/>

### 3. 개발 (선택): 유효성 검사 및 에러 처리
- [x] 1. 에러 처리 (에러 처리 미들웨어)
- [x] 2. 유효성 검증 (Joi)
<br/>

---

<br/>

### 4. 테스트: API Client로 동작 확인
- [x] 1. 테스트: API Client로 동작 확인

<br/>

---

<br/>

### 5. 배포: 누구나 이용할 수 있도록 하기
- [x] 1. 배포: 누구나 이용할 수 있도록 하기

<br/>

---

<br/>

### 6. 과제 제출 질문  답변
- Q) 11. 비밀번호 저장 시 평문으로 저장하면 DB 유출 시 문제가 됩니다. 어떻게 저장해야 안전하게 저장할 수 있을까요?
- A) 암호화 와 해싱은 조금 다른 개념입니다. 해싱은 일방향 으로 해싱이 되면 원래 값을 복원 할 수 없고 암화화는 키를 사용해서 복원 할 수 있어서 비밀번호는 암호화 보다는 해싱을 통해서 복원 할 수 없도록 하는것이 더 좋습니다.

<br/>

---

<br/>

### 7. 더 나아가기
- 필수, 선택 요구사항을 잘 구현하셨습니다. 
- 앞에서 말씀드린 비밀번호 해싱을 한번 구현 해보세요. 
- Validation 코드 분리 
  -  미들웨어에 validation.middleware.js 를 만들고 필요한 곳에서 사용할 수 있도록 코드를 분리시켜주세요.
- 상품 수정에서 req.body 말고 사용자가 입력한 데이터만 뽑고 PUT 말고 PATCH 메서들 이용해서 수정하도록 코드 작성해주세요.

**Comment by fierceCry** [comment]
피드백 수정과 패스워드 암호화, 유효성 검사 코드 분리, 상품수정 PATCH 코드 수정 완료했습니다!!

**Comment by jyh7a** [comment]
네 수고 많으셨습니다. 

올려 준 코드에서 error middleware에서 오류 처리를 하기때문에 
라우터 내부에서 다시 try-catch 를 사용 할 필요는 없어보입니다.
라우터 내부에 try-catch를 제거하고도 비동기 에러가 잘 처리하는지 테스트 후에 
error는 error middleware에서 한번에 관리하는 방식으로 변경해 보세요~

```javascript 
// 모든 상품 조회
router.get('/products', catchAsync(async (req, res) => {
    try {
      const data = await product
        .find()
        .select('-password')
        .sort({ createdAt: -1 })
        .exec();
      return res.status(200).json({ products: data });
    } catch {
      return res.status(500).json({
        message: '예상치 못한 에러가 발생했습니다. 관리자에게 문의해 주세요.',
      });
    }
  }),
);
```

**Comment by fierceCry** [comment]
모든 API에서 try-catch를 제거한 후 error middleware가 제대로 작동하는지 테스트한 결과, 잘 처리되고 있음을 확인했습니다. 이전에 말씀해주신 git commit message convention에 맞게 커밋을 작성했습니다. 현재는 프로젝트의 마지막 단계에 와서 커밋 메시지를 일관되게 작성하지 못한 부분이 있지만, 다음부터는 convention에 맞게 작성하도록 하겠습니다.
